### ISSUE TITLE
Promatic 4 pinout?

### ISSUE THREAD

**Issue by Trilis29** [14yannick/HCPBridgeMqtt#4]
Is the pinout numbering correct? Something not right for me. I do not receive 24v on BUS scan.
Promatic 4.
Tried measuring with multimeter max was 3.3v

**Comment by 14yannick** [comment]
If your ground is on 1 & 2 or 5 & 6 could depend on your cable (straight or Cross-over). But B is next to ground and A next to power. 
You should also have a terminal next to the bus. with following assignment:
- 23 Signal channel 2 Partial opening
- 5 +24 V DC
- 21 Signal channel 1 Impulse
- 20 Ground
Measure with your multimeter the value you have between 5 and 20. You should get the same on the bus during bus scan.

**Comment by 14yannick** [comment]
Ensure your multimeter is in dc mode  (I made this mistake once).

**Comment by Trilis29** [comment]
I made the cable myself, so I know the colors and pins, but still not getting 24V... That is the problem. DC-DC buck converter not even lighting up. 
I think I will try to give power from 5 and 20 terminal to powerup everything and then will try to run BUS scan.

Then question, do I need to pin 24v and Ground cables from RJ12 cable aswell? Or voltage is enough from another terminal?

**Comment by 14yannick** [comment]
Where you able to get it work?

**Comment by Tysonpower** [comment]
I also got a Promatic 4 unit, just got my PCBs today and tested it, the Pinout is the same as on the Supramatic units/What is mentioned in the repo. In my case the cable Colors where flipped, so i had to resolder them once backwards :)

**Comment by 14yannick** [comment]
It depend on the PDB design you used. If you take mine (Ugly big one) the calbe needs to be reversed. With the nice PcB design from vladimirzrnic the cable needs to be Straight. 
Does your led flash 7 times. See below link.
https://www.tor7.de/news/hilfe-zu-fehler-und-meldungen-beim-promatic-gragentorantrieb
If yes it could be the problem we are trying to identify here.
https://github.com/Gifford47/HCPBridgeMqtt/issues/11
Does the led directly start to flash as soon you turn on your motor or does it happen only after a random time of use. Please reply in the other issue as I will close this one.

**Comment by Tysonpower** [comment]
i have the PCb from vladimirzrnic, will write in the other issue, happy you are still working on the software :)
